In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('statdata.csv')
df

     name  study_hours  student_marks   gpa
0    Akas         5.67          71.82  2.99
1    Bina         8.67          84.19  3.99
2  Sweety         7.55          81.18  3.07
3   Kamal         6.67          76.99  3.93
4   Jamal         8.99          85.46  3.99
5   Tamal         5.19          70.66  2.43
6   Bijon         6.75          77.82  3.55
7   Farid         6.59          75.37  3.67
8   Rubel         8.56          83.88  2.97
9    Rina         7.75          79.50  3.81

### **Find Count, Min, Max, Sum, Cumsum**

In [4]:
df.count()

name             10
study_hours      10
student_marks    10
gpa              10
dtype: int64

In [5]:
df.min()

name              Akas
study_hours       5.19
student_marks    70.66
gpa               2.43
dtype: object

In [6]:
df.max()

name             Tamal
study_hours       8.99
student_marks    85.46
gpa               3.99
dtype: object

In [7]:
df.student_marks.sum()

np.float64(786.87)

In [8]:
df.student_marks.cumsum()

0     71.82
1    156.01
2    237.19
3    314.18
4    399.64
5    470.30
6    548.12
7    623.49
8    707.37
9    786.87
Name: student_marks, dtype: float64

### **Find Mean, Median, Mode**

In [18]:
df[['student_marks','study_hours','gpa']].mean()

student_marks    78.687
study_hours       7.239
gpa               3.440
dtype: float64

In [ ]:
# Mean
df.gpa.mean()

np.float64(3.44)

In [ ]:
# Median
df.gpa.median()

np.float64(3.61)

In [23]:
# Mode
df.gpa.mode()

0    3.99
Name: gpa, dtype: float64

In [19]:
df[['student_marks','study_hours','gpa']].mean()

student_marks    78.687
study_hours       7.239
gpa               3.440
dtype: float64

In [20]:
df[['student_marks','study_hours','gpa']].median()

student_marks    78.66
study_hours       7.15
gpa               3.61
dtype: float64

In [21]:
df[['student_marks','study_hours','gpa']].mode()

   student_marks  study_hours   gpa
0          70.66         5.19  3.99
1          71.82         5.67   NaN
2          75.37         6.59   NaN
3          76.99         6.67   NaN
4          77.82         6.75   NaN
5          79.50         7.55   NaN
6          81.18         7.75   NaN
7          83.88         8.56   NaN
8          84.19         8.67   NaN
9          85.46         8.99   NaN

### **Variance and Standard Deviation**

In [ ]:
# Variance
df.study_hours.var()

np.float64(1.6512099999999998)

In [ ]:
# Standard Deviation
df.study_hours.std()

np.float64(1.2849941634108693)

### **Quantile**

In [16]:
df[['student_marks','study_hours', 'gpa']].quantile(.25)

student_marks    75.775
study_hours       6.610
gpa               3.010
Name: 0.25, dtype: float64

### **IQR**

In [17]:
q1 = df[['student_marks','study_hours', 'gpa']].quantile(.25)
q3 = df[['student_marks','study_hours', 'gpa']].quantile(.75)
iqr = q3 - q1
iqr

student_marks    7.4300
study_hours      1.7475
gpa              0.8900
dtype: float64